language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: AJXmpQEyDbZy43Ayzc71NHfUv7i/yj6kXEhL+9saBse8iw2X0B7B2oOoqqp4fZqOzgfiwHhcQ80Sv8VBVa619ZrUIbza++zfXbmtVfuGWgWFsk7GZzzcEng0wzaV06GIM+b4VpS+0ze6FrCwQ59P9146q8lCax4qG8vBW7fz6VrLRkzaq9ZVxdztLdYPGpG7/R3bIGpeD/TwADviKB+FiQ+hl1BaJZsxsbyNBL3eeXdD4GXiA9k1mwsDFpHGFdkYRGUTlKxvpTlung2FkbfRZuiYS7eJKIMr2y75VCx6JdoemPNKHswkjYi29El+oayKNYmA2uxvm9m7vHkl/4hS+QKEWAD2c0aSUkxem9PxEpeg/0N1iqebD+faOlZqmYjxwGn/Cx0ydPfeO8kb8Lmku3Pm/zbcPDi1zuoFz0mt9hniJgP8mm1uR47pNV8Zf3aqWWMj9Ab4ij67C9f3r+z+Sia8IweKLHxPwIUnlK3L64DpmpQsKJELHZ6tnvd7B7cdXXb6DOahvI8Rugvt4ixXVus08/m93Yowz+v0Q7Injvq/KihuWJcMlQ/4chCVCakVX499NEgxcRrgHq/sXWy2ZhfTjfBC0ACvjI9nUDdX/qAd5o7hk6FKZwVcqAnguAQS3pd3wSlplT6iqM+OeRg+FHy2NAs1OaDTS5pVvpy1JqA=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
